# yaml-language-server: $schema=https://www.rubyschema.org/rubocop.json
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  DisabledByDefault: true
  SuggestExtensions: false