AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  DisabledByDefault: true
  SuggestExtensions: false

inherit_from: "https://www.goodcop.style/base.yml"

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'test/**/*'