require:
 - rubocop-minitest
 - rubocop-rake

AllCops:
  Exclude:
    - inline.rb
    - test/simulation.rb
    - vendor/bundle/**/*
  TargetRubyVersion: 2.7
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Gemspec/DevelopmentDependencies:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/NegatedIf:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*_test.rb

Naming/VariableNumber:
  Exclude:
    - test/**/*_test.rb

Style/SingleLineMethods:
  Exclude:
    - test/**/*_test.rb

Lint/ConstantDefinitionInBlock:
  Exclude:
    - test/**/*_test.rb